- name: Install debconf-utils
  apt:
    name: debconf-utils       #allow you set the password before installing so no need to provide manually  during setup.
    state: present
    update_cache: yes

- name: Preseed MySQL root password
  shell: |
    echo "mysql-server mysql-server/root_password password {{ mysql_password }}" | debconf-set-selections         #Set MySQL root password 
    echo "mysql-server mysql-server/root_password_again password {{ mysql_password }}" | debconf-set-selections   #Confirm MySQL root password 
  args:
    executable: /bin/bash

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present          #Install the MySQL server package

- name: Enable and start MySQL service
  systemd:
    name: mysql                
    enabled: yes               # Enable MySQL service to start automatically on system boot
    state: started             # Start the MySQL service immediately
