- name: Install PHP and modules
  apt:
    name:
      - php                # Install the main PHP package
      - php-mysql          # Install PHP module to connect PHP with MySQL databases
      - libapache2-mod-php # Install Apache module to run PHP scripts through Apache
    state: present
    update_cache: true

- name: Restart Apache to load PHP module
  service:
    name: apache2
    state: restarted     # Restart Apache to apply changes and load new PHP module
